"""Adaptive ladder: persistence, ordering, and engine wiring."""
from __future__ import annotations

import json

import requests

from waf_requests import learn
from waf_requests.engine import WAFSession

CLOUDFRONT_BLOCK = (
    b"<html><body>ERROR: The request could not be satisfied.</body></html>"
    b"Generated by cloudfront (CloudFront)"
)
SQLI = "' OR '1'='1"


def _blocked():
    return (403, CLOUDFRONT_BLOCK, {"Content-Type": "text/html"})


def _delivered():
    return (200, b'{"ok": true}', {"Content-Type": "application/json"})


class ScriptedAdapter(requests.adapters.HTTPAdapter):
    def __init__(self, responses):
        super().__init__()
        self.responses = list(responses)
        self.sent = []

    def send(self, request, **kwargs):  # type: ignore[override]
        self.sent.append((request.method, request.url, dict(request.headers)))
        resp = requests.Response()
        resp.status_code, resp._content, headers = self.responses.pop(0)
        resp.headers.update(headers)
        resp.request = request
        return resp


def test_record_win_round_trips(tmp_path, monkeypatch):
    monkeypatch.setenv("WAF_REQUESTS_LEARN_FILE", str(tmp_path / "learned.json"))
    learn.record_win("t.test", "percent_double_encode")
    assert learn.load_learned() == {"t.test": ["percent_double_encode"]}


def test_learned_order_promotes_existing_but_not_new(tmp_path, monkeypatch):
    monkeypatch.setenv("WAF_REQUESTS_LEARN_FILE", str(tmp_path / "learned.json"))
    learn.record_win("t.test", "hpp_duplicate_param")
    order = learn.learned_order("t.test", ("a", "b", "hpp_duplicate_param"))
    assert order == ("hpp_duplicate_param", "a", "b")


def test_learned_order_uses_default_for_unknown_host(tmp_path, monkeypatch):
    monkeypatch.setenv("WAF_REQUESTS_LEARN_FILE", str(tmp_path / "learned.json"))
    assert learn.learned_order("other.test", ("a", "b")) == ("a", "b")


def test_record_win_caps_and_dedupes(tmp_path, monkeypatch):
    monkeypatch.setenv("WAF_REQUESTS_LEARN_FILE", str(tmp_path / "learned.json"))
    for tid in ("a", "b", "a", "c"):
        learn.record_win("t.test", tid)
    wins = learn.load_learned()["t.test"]
    assert wins == ["c", "a", "b"]  # most-recent first, deduped
    assert wins[0] == "c"


def test_engine_promotes_winning_transform_on_second_call(monkeypatch, tmp_path):
    monkeypatch.setenv("WAF_REQUESTS_LEARN_FILE", str(tmp_path / "learned.json"))
    s = WAFSession(profile="aws", learn=True)
    # Call 1: applicable transforms for a GET query are header_pad_early,
    # hpp_duplicate_param, percent_double_encode (others return None).
    s.mount("http://", ScriptedAdapter([
        _blocked(),      # original
        _blocked(),      # header_pad_early
        _blocked(),      # hpp_duplicate_param
        _delivered(),    # percent_double_encode -> win
    ]))
    r1 = s.get(f"http://t.test/search?q={requests.utils.quote(SQLI, safe='')}")
    assert r1.status_code == 200
    assert learn.load_learned()["t.test"][0] == "percent_double_encode"

    # Call 2: percent_double_encode must now run immediately after original.
    s.mount("http://", ScriptedAdapter([
        _blocked(),      # original
        _delivered(),    # percent_double_encode (promoted)
    ]))
    r2 = s.get(f"http://t.test/search?q={requests.utils.quote(SQLI, safe='')}")
    assert r2.waf_attempts[1].transform_id == "percent_double_encode"
    assert len(r2.waf_attempts) == 2


def test_learn_file_corrupt_returns_empty(tmp_path, monkeypatch):
    p = tmp_path / "learned.json"
    p.write_text("{ not json")
    monkeypatch.setenv("WAF_REQUESTS_LEARN_FILE", str(p))
    assert learn.load_learned() == {}
    # file shape round-trips as json when persisted
    learn.record_win("t.test", "a")
    assert json.loads(p.read_text()) == {"t.test": ["a"]}
