"""Engine ladder behavior and block-page classification."""
from __future__ import annotations

import json

import pytest
import requests

from waf_requests.engine import WAFSession
from waf_requests.blockpage import Status, classify

CLOUDFRONT_BLOCK = (
    b"<html><body>ERROR: The request could not be satisfied.</body></html>"
    b"Generated by cloudfront (CloudFront)"
)


class ScriptedAdapter(requests.adapters.HTTPAdapter):
    """Returns canned responses; records every prepared request."""

    def __init__(self, responses):
        super().__init__()
        self.responses = list(responses)
        self.sent = []

    def send(self, request, **kwargs):  # type: ignore[override]
        self.sent.append((request.method, request.body, dict(request.headers)))
        status, body, headers = self.responses.pop(0)
        resp = requests.Response()
        resp.status_code = status
        resp._content = body
        resp.headers.update(headers)
        resp.request = request
        return resp


def blocked():
    return (403, CLOUDFRONT_BLOCK, {"Content-Type": "text/html"})


def delivered(body=b'{"ok": true}'):
    return (200, body, {"Content-Type": "application/json"})


def json_session(adapter, **session_kwargs) -> WAFSession:
    session = WAFSession(profile="aws", max_attempts=6, **session_kwargs)
    session.mount("http://", adapter)
    return session


def post_spec_url() -> str:
    return "http://engine.test/echo"


def test_ladder_retries_until_delivered_and_records_attempts():
    adapter = ScriptedAdapter([blocked(), blocked(), delivered()])
    session = json_session(adapter)
    payload = json.dumps({"q": "' OR '1'='1"}).encode()
    prepared = requests.PreparedRequest()
    prepared.prepare(
        method="POST", url=post_spec_url(),
        data=payload, headers={"Content-Type": "application/json"},
    )
    resp = session.send(prepared)
    assert len(adapter.sent) == 3                      # original + 2 transforms
    assert resp.status_code == 200
    attempts = resp.waf_attempts
    assert [a.transform_id for a in attempts] == [
        None, "pad_json_ws", "json_unicode_escape",
    ]
    # New fidelity-safe ladder: pad_form_param is skipped (JSON), and
    # json_unicode_escape now precedes the differential tail.
    assert attempts[0].status is Status.BLOCKED
    assert attempts[-1].status is Status.DELIVERED


def test_retry_mutating_false_stops_after_first_block():
    adapter = ScriptedAdapter([blocked(), delivered(), delivered()])
    session = WAFSession(profile="aws", retry_mutating=False)
    session.mount("http://", adapter)
    prepared = requests.PreparedRequest()
    prepared.prepare(method="POST", url=post_spec_url(),
                     data=b"q=1", headers={"Content-Type": "application/x-www-form-urlencoded"})
    resp = session.send(prepared)
    assert len(adapter.sent) == 1
    assert resp.status_code == 403
    assert resp.waf_attempts[0].status is Status.BLOCKED


def test_idempotent_methods_retry_even_with_retry_mutating_false():
    adapter = ScriptedAdapter([blocked(), delivered()])
    session = WAFSession(profile="aws", retry_mutating=False)
    session.mount("http://", adapter)
    prepared = requests.PreparedRequest()
    prepared.prepare(method="GET", url="http://engine.test/search?q=1%27+OR+%271")
    resp = session.send(prepared)
    assert len(adapter.sent) == 2
    assert resp.status_code == 200


def test_exhausted_ladder_returns_last_blocked():
    responses = [blocked()] * 3 + [delivered()]
    adapter = ScriptedAdapter(responses)
    session = WAFSession(profile="aws", max_attempts=3)
    session.mount("http://", adapter)
    prepared = requests.PreparedRequest()
    prepared.prepare(method="GET", url="http://engine.test/search?q=x")
    resp = session.send(prepared)
    assert len(adapter.sent) == 3
    assert resp.status_code == 403
    assert all(a.status is Status.BLOCKED for a in resp.waf_attempts)


def test_unknown_ladder_ids_rejected_at_construction():
    with pytest.raises(ValueError, match="unknown transform ids"):
        WAFSession(profile="aws", ladder=("nope",))


def test_off_profile_sends_once_untouched():
    adapter = ScriptedAdapter([delivered()])
    session = WAFSession(profile="off")
    session.mount("http://", adapter)
    prepared = requests.PreparedRequest()
    prepared.prepare(method="GET", url="http://engine.test/a")
    resp = session.send(prepared)
    assert len(adapter.sent) == 1
    assert resp.status_code == 200
    assert not hasattr(resp, "waf_attempts")


# --- classification ----------------------------------------------------------

def _resp(status, body: bytes, headers=None):
    r = requests.Response()
    r.status_code = status
    r._content = body
    for k, v in (headers or {}).items():
        r.headers[k] = v
    return r


def test_cloudflare_mitigated_header():
    assert classify(_resp(403, b"", {"cf-mitigated": "block"})).vendor == "cloudflare"
    v = classify(_resp(403, b"", {"cf-mitigated": "challenge"}))
    assert v.status is Status.CHALLENGE


def test_cloudflare_error_code_block():
    v = classify(_resp(403, b"error code: 1010\n",
                       {"Server": "cloudflare", "CF-RAY": "abc123-TLV"}))
    assert v.vendor == "cloudflare" and v.status is Status.BLOCKED


def test_cloudflare_error_code_requires_edge_header():
    # "error code: 1010" without a Cloudflare edge header is app-ambiguous.
    assert classify(_resp(403, b"error code: 1010\n")).status is Status.UNKNOWN


def test_akamai_reference_regex():
    body = b"<html>Access Denied. Reference #97.5e2c1f23.1756000000.3f2a</html>"
    v = classify(_resp(403, body, {"Server": "AkamaiGHost"}))
    assert v.vendor == "akamai" and v.status is Status.BLOCKED

def test_aws_cloudfront_block_page():
    v = classify(_resp(403, CLOUDFRONT_BLOCK))
    assert v.vendor == "aws" and v.status is Status.BLOCKED


def test_bare_403_is_unknown_not_blocked():
    v = classify(_resp(403, b"Forbidden"))
    assert v.status is Status.UNKNOWN and v.vendor is None


def test_normal_200_delivered():
    assert classify(_resp(200, b"<html>hello</html>")).status is Status.DELIVERED
