"""Classify a response as delivered, blocked, challenge, or unknown."""
from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum


class Status(str, Enum):
    DELIVERED = "DELIVERED"
    BLOCKED = "BLOCKED"
    CHALLENGE = "CHALLENGE"
    UNKNOWN = "UNKNOWN"


@dataclass(frozen=True)
class Verdict:
    status: Status
    vendor: "str | None"
    evidence: str


_CF_BODY_MARKERS: "tuple[tuple[str, Status], ...]" = (
    ("__cf_chl_opt", Status.CHALLENGE),
    ("cf-challenge", Status.CHALLENGE),
    ("cf-error-details", Status.BLOCKED),
    ("attention required", Status.BLOCKED),
)

#: Cloudflare plain-text denials: ``error code: 1010`` (UA/browser ban),
#: ``1006`` (IP ban), ``1015`` (rate limit), ``1020`` (custom firewall rule).
#: These have no HTML body, so the marker table above never sees them.
_CF_ERROR_CODE = re.compile(r"error code:\s*(\d+)")

_AKAMAI_REFERENCE = re.compile(r"Reference #[0-9a-f]+\.[0-9a-f]+\.[0-9a-f]+", re.IGNORECASE)
_CLOUDFRONT_BLOCK = "error: the request could not be satisfied"


def _value(headers: dict, name: str, substring: str) -> bool:
    return substring in str(headers.get(name, "")).lower()


def _cookie(headers: dict) -> str:
    return str(headers.get("set-cookie", "")).lower()


def _has_header(headers: dict, name: str) -> bool:
    return any(str(k).lower() == name for k in headers)


def _imperva(headers, status_code, text):
    if ("visid_incap_" in _cookie(headers) or "incap_ses_" in _cookie(headers)
            or _has_header(headers, "x-iinfo") or _value(headers, "x-cdn", "incap")
            or "incapsula" in text):
        return Verdict(Status.BLOCKED, "imperva", "Incapsula cookie/header/body marker")
    return None


def _f5(headers, status_code, text):
    if ("bigipserver" in _cookie(headers) or _has_header(headers, "x-wa-info")
            or "the requested url was rejected" in text):
        return Verdict(Status.BLOCKED, "f5", "BIG-IP ASM cookie/header/reject page")
    return None


def _fortiweb(headers, status_code, text):
    if "fortiweb=" in _cookie(headers) or "fortiweb" in text:
        return Verdict(Status.BLOCKED, "fortiweb", "FortiWeb cookie/body marker")
    return None


def _barracuda(headers, status_code, text):
    if _value(headers, "server", "barracuda") or "barra_counter_session" in _cookie(headers):
        return Verdict(Status.BLOCKED, "barracuda", "Barracuda server/cookie marker")
    return None


def _citrix(headers, status_code, text):
    if ("nsc_" in _cookie(headers) or "request prohibited" in text
            or "ns_violation" in text):
        return Verdict(Status.BLOCKED, "citrix", "NetScaler cookie/body marker")
    return None


def _radware(headers, status_code, text):
    if _has_header(headers, "x-radware") or _has_header(headers, "x-sl-compstate"):
        return Verdict(Status.BLOCKED, "radware", "Radware response header")
    return None


def _wordfence(headers, status_code, text):
    if ("your access to this site has been limited by the wordfence firewall" in text
            or "generated by wordfence" in text):
        return Verdict(Status.BLOCKED, "wordfence", "Wordfence block page")
    return None


def _sucuri(headers, status_code, text):
    if ("sucuri/cloudproxy" in str(headers.get("server", "")).lower()
            or _has_header(headers, "x-sucuri-id")
            or "sucuri website firewall" in text):
        return Verdict(Status.BLOCKED, "sucuri", "Sucuri header/body marker")
    return None


def _modsecurity(headers, status_code, text):
    server = str(headers.get("server", "")).lower()
    if (status_code == 403 and ("nginx" in server or "apache" in server)
            and ("forbidden" in text or "not acceptable" in text)):
        return Verdict(Status.BLOCKED, "modsecurity", "403 + generic server + forbidden body")
    return None


#: Vendor signature matchers, most-explicit first, heuristic (modsecurity) last.
_VENDOR_SIGNATURES: "list[tuple[str, object]]" = [
    ("imperva", _imperva),
    ("f5", _f5),
    ("fortiweb", _fortiweb),
    ("barracuda", _barracuda),
    ("citrix", _citrix),
    ("radware", _radware),
    ("wordfence", _wordfence),
    ("sucuri", _sucuri),
    ("modsecurity", _modsecurity),
]


def classify(resp) -> Verdict:
    """Inspect one response for managed-WAF block/challenge signatures.

    Deliberately conservative: a bare 403 with no recognizable signature is
    UNKNOWN, never BLOCKED, because application 403s look identical. Callers
    that need ground truth should observe the origin (see lab/vulnapp).
    """
    headers = getattr(resp, "headers", None) or {}
    status_code = getattr(resp, "status_code", 0)
    content = getattr(resp, "content", b"") or b""
    body = content[:65536]
    text = body.decode("utf-8", errors="replace").lower()

    cf_mitigated = headers.get("cf-mitigated")
    if cf_mitigated:
        value = str(cf_mitigated).strip().lower()
        if value == "challenge":
            return Verdict(Status.CHALLENGE, "cloudflare", "cf-mitigated: challenge")
        if value == "block":
            return Verdict(Status.BLOCKED, "cloudflare", "cf-mitigated: block")

    for marker, marker_status in _CF_BODY_MARKERS:
        if marker in text:
            return Verdict(marker_status, "cloudflare", f"body marker {marker!r}")

    error_code = _CF_ERROR_CODE.search(text)
    if error_code and (headers.get("cf-ray") or str(headers.get("server", "")).lower() == "cloudflare"):
        return Verdict(Status.BLOCKED, "cloudflare", f"error code {error_code.group(1)}")

    reference = _AKAMAI_REFERENCE.search(text)
    if reference:
        return Verdict(Status.BLOCKED, "akamai", reference.group(0))

    server = str(headers.get("server", "")).lower()
    if "akamai" in server or any(str(k).lower().startswith("x-akamai") for k in headers):
        if status_code in (403, 503):
            return Verdict(Status.BLOCKED, "akamai", f"akamai edge + status {status_code}")
        if "access denied" in text:
            return Verdict(Status.BLOCKED, "akamai", "Access Denied + akamai header")

    if _CLOUDFRONT_BLOCK in text:
        return Verdict(Status.BLOCKED, "aws", "CloudFront 'request could not be satisfied' page")

    set_cookie = str(headers.get("set-cookie", ""))
    if "awswaf=" in set_cookie:
        return Verdict(Status.CHALLENGE, "aws", "awswaf challenge cookie issued")

    for _vendor, matcher in _VENDOR_SIGNATURES:
        verdict = matcher(headers, status_code, text)
        if verdict is not None:
            return verdict

    if status_code == 403 and len(body) < 256:
        return Verdict(
            Status.UNKNOWN, None,
            "bare 403 with empty/small body - ambiguous vs app 403",
        )

    return Verdict(Status.DELIVERED, None, "no block signatures")
