"""Stamp a `## Wire example` section into every technique page.

Examples are GENERATED by applying the real transform to a representative
request, so the before/after bytes on each docs page can never drift from the
implementation. Idempotent: existing sections are replaced, not duplicated.

Run: .venv/bin/python scripts/stamp_wire_examples.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from waf_requests import TRANSFORMS, Ctx  # noqa: E402
from waf_requests.fidelity import tier_of  # noqa: E402
from waf_requests.spec import ReqSpec, to_prepared  # noqa: E402

SQLI = "' OR '1'='1"
DOCS = Path(__file__).resolve().parents[1] / "docs" / "techniques"
DISPLAY_LIMIT = 256  # shrink pad geometry so printouts stay readable


def json_spec():
    return ReqSpec("POST", "http://shop.test/search",
                   {"Content-Type": "application/json"},
                   json.dumps({"q": SQLI}).encode())


def form_spec():
    return ReqSpec("POST", "http://shop.test/search",
                   {"Content-Type": "application/x-www-form-urlencoded"},
                   f"q={SQLI}".encode())


def multipart_spec():
    boundary = "XyZ123"
    body = (
        f"--{boundary}\r\n"
        'Content-Disposition: form-data; name="q"\r\n\r\n'
        f"{SQLI}\r\n"
        f"--{boundary}--\r\n"
    ).encode()
    return ReqSpec("POST", "http://shop.test/upload",
                   {"Content-Type": f"multipart/form-data; boundary={boundary}"}, body)


def two_part_multipart():
    b = "B2"
    body = (
        f"--{b}\r\n"
        'Content-Disposition: form-data; name="first"\r\n\r\none\r\n'
        f"--{b}\r\n"
        'Content-Disposition: form-data; name="second"\r\n\r\ntwo\r\n'
        f"--{b}--\r\n"
    ).encode()
    return ReqSpec("POST", "http://shop.test/upload",
                   {"Content-Type": f"multipart/form-data; boundary={b}"}, body)


def get_spec():
    from urllib.parse import quote

    return ReqSpec("GET", "http://shop.test/search?q=" + quote(SQLI, safe=""),
                   {"User-Agent": "exploit/1.0"}, None)


def two_pair_query():
    return ReqSpec("GET", "http://shop.test/s?a=1&q=" + SQLI.replace(" ", "+"),
                   {}, None)


def dotted_path():
    return ReqSpec("GET", "http://shop.test/a/b.c", {}, None)


def slashy_path():
    return ReqSpec("GET", "http://shop.test/a/b", {}, None)


def traversal_spec():
    return ReqSpec("GET", "http://shop.test/files/../secret.txt",
                   {"User-Agent": "exploit/1.0"}, None)


def plain_file_spec():
    return ReqSpec("GET", "http://shop.test/files/report.txt", {}, None)


def ua_spec():
    return ReqSpec("GET", "http://shop.test/search",
                   {"User-Agent": "<script>alert(1)</script>"}, None)


FIXTURES = {
    "pad_json_ws": (json_spec, Ctx(profile_limit=DISPLAY_LIMIT)),
    "json_unicode_escape": (json_spec, Ctx(profile_limit=None)),
    "gzip_body": (json_spec, Ctx(profile_limit=None)),
    "deflate_body": (json_spec, Ctx(profile_limit=None)),
    "charset_utf7": (json_spec, Ctx(profile_limit=None)),
    "json_dup_key_lastwins": (json_spec, Ctx(profile_limit=None)),
    "json_deep_nest_wrap": (json_spec, Ctx(profile_limit=None)),
    "json_comment_inject": (json_spec, Ctx(profile_limit=None)),
    "pad_form_param": (form_spec, Ctx(profile_limit=DISPLAY_LIMIT)),
    "pad_multipart_decoy": (multipart_spec, Ctx(profile_limit=DISPLAY_LIMIT)),
    "multipart_boundary_variance": (multipart_spec, Ctx(profile_limit=None)),
    "multipart_payload_last": (two_part_multipart, Ctx(profile_limit=None)),
    "percent_double_encode": (get_spec, Ctx(profile_limit=None)),
    "hpp_duplicate_param": (get_spec, Ctx(profile_limit=None)),
    "hpp_semicolon_sep": (two_pair_query, Ctx(profile_limit=None)),
    "utf8_overlong_path": (dotted_path, Ctx(profile_limit=None)),
    "path_semicolon_params": (get_spec, Ctx(profile_limit=None)),
    "path_dot_segments": (get_spec, Ctx(profile_limit=None)),
    "path_double_slash": (slashy_path, Ctx(profile_limit=None)),
    "header_pad_early": (ua_spec, Ctx(profile_limit=DISPLAY_LIMIT)),
    "dup_header_firstlast": (ua_spec, Ctx(profile_limit=None)),
    "method_override": (get_spec, Ctx(profile_limit=None)),
    "path_dotdot_semicolon": (traversal_spec, Ctx(profile_limit=None)),
    "path_collapse_dotdot": (traversal_spec, Ctx(profile_limit=None)),
    "null_byte_terminator": (plain_file_spec, Ctx(profile_limit=None)),
    "spoof_trusted_ip": (ua_spec, Ctx(profile_limit=None)),
}

# Transforms whose output is too tall for the default body preview window.
BODY_PREVIEW_OVERRIDES = {
    "json_deep_nest_wrap": 220,
}


def _collapse(text: str) -> str:
    """Shrink filler runs (spaces, AAAA..., [[[[...) to counted markers.

    Long irrelevant runs become `<Nx 'c'>`; everything else - especially
    payload characters - stays byte-for-byte.
    """
    import re as _re

    def sub(match):
        run = match.group(0)
        return f"<{len(run)}x {run[0]!r}>"

    return _re.sub(r"(.)\1{23,}", sub, text)


def render(prep, max_body=170) -> str:
    """Origin-form wire; filler collapsed; head+tail kept on cut."""
    from urllib.parse import urlsplit

    parts = urlsplit(prep.url)
    target = parts.path or "/"
    if parts.query:
        target += "?" + parts.query
    lines = [f"{prep.method} {target} HTTP/1.1", f"Host: {parts.netloc}"]
    for key, value in prep.headers.items():
        shown_value = _collapse(str(value))
        if len(shown_value) > 110:
            cut = len(shown_value) - 100
            shown_value = shown_value[:60] + f" ...[{cut} chars hidden]... " \
                + shown_value[-40:]
        lines.append(f"{key}: {shown_value}")
    body = prep.body or b""
    if isinstance(body, str):
        body = body.encode()
    if body:
        try:
            text = body.decode("utf-8")
            nonprintable = sum(
                not c.isprintable() and c not in "\r\n\t" for c in text)
            if nonprintable > len(text) * 0.3:
                raise UnicodeDecodeError("utf-8", body, 0, 1, "binary-ish")
        except UnicodeDecodeError:
            encoding = next((str(v) for k, v in prep.headers.items()
                             if k.lower() == "content-encoding"), "")
            lines.append("")
            lines.append(f"<{len(body)} bytes of {encoding or 'binary'} data>")
            return "\n".join(lines)
        text = _collapse(text.replace("\r\n", "\n"))
        lines.append("")
        if len(text) > max_body:
            half = max_body // 2
            lines.append(text[:half].rstrip("\n"))
            lines.append("...[filler-only bytes hidden]...")
            lines.append(text[-half:].lstrip("\n"))
        else:
            lines.append(text)
    return "\n".join(lines)

IMPACT_TEXT = {
    "transparent": (
        "**Impact: guaranteed.** Once this transform delivers, a conforming"
        "\norigin has interpreted the ORIGINAL payload byte-for-byte - the"
        "\nexploit lands regardless of application stack."),
    "additive": (
        "**Impact: guaranteed for the original fields.** Decoys are extra"
        "\ndistinct-name parameters/parts no exploit reads."),
    "differential": (
        "**Impact: conditional.** The wire payload DIFFERS from the original;"
        "\nthe origin interprets it correctly only if its parser behaves as"
        "\ndocumented here. Delivery alone is not exploitation - prove it with"
        "\n`python -m waf_requests verify <url>`."),
}


def upsert_section(page: Path) -> str:
    text = page.read_text()
    anchor = "## Prerequisites and limits"
    assert anchor in text, page.name
    block = section_for(page.stem)
    start = text.find("## Wire example")
    if start >= 0:
        text = text[:start] + block + "\n" + text[text.find(anchor):]
        action = "replaced"
    else:
        text = text.replace(anchor, block + "\n" + anchor, 1)
        action = "inserted"

    import re as _re

    tier = tier_of(page.stem)
    impact = f"> **Impact:** {IMPACT_TEXT[tier]}"
    if "> **Impact:**" in text:
        text = _re.sub(r"> \*\*Impact:\*\*[^\n]*(\n[^\n>#][^\n]*)*", impact, text,
                       count=1)
    else:
        text = _re.sub(r"^(Category: .*)$", r"\1\n\n" + impact, text,
                       count=1, flags=_re.M)
    page.write_text(text)
    return action


def section_for(tid: str) -> str:
    factory, ctx = FIXTURES[tid]
    spec = factory()
    out = TRANSFORMS[tid].apply(spec, ctx)
    assert out is not None, tid
    tier = tier_of(tid)
    note = ""
    if ctx.profile_limit == DISPLAY_LIMIT and "pad" in tid or tid == "header_pad_early":
        note = (f"\nThe inspection window is shrunk to {DISPLAY_LIMIT} bytes here so"
                "\nthe pad geometry fits on screen.")
    max_body = BODY_PREVIEW_OVERRIDES.get(tid, 170)
    return (
        f"## Wire example\n\n"
        f"Generated by applying this transform to a representative request "
        f"(fidelity tier: **{tier}**).{note}\n\n"
        f"Original:\n\n```http\n{render(to_prepared(spec), max_body)}\n```\n\n"
        f"After `{tid}`:\n\n```http\n{render(to_prepared(out), max_body)}\n```\n"
    )




def main() -> int:
    counts = {"inserted": 0, "replaced": 0}
    for tid in sorted(TRANSFORMS):
        action = upsert_section(DOCS / f"{tid}.md")
        counts[action] += 1
    print(f"inserted={counts['inserted']} replaced={counts['replaced']} "
          f"total={len(TRANSFORMS)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
